type TextChannel {
	_id: ID!
	name: String!
	messages: [Message]
}

type Message {
	textChannelId: ID!
	sender: User!
	content: String!
}

input newMessageInput {
	textChannelId: ID!
	content: String!
}

extend type Mutation {
	sendMessage(input: newMessageInput): Message @isAuth
}

type Subscription {
	sendedMessage(channelsIds: [ID!]!): Message
}
