language: node_js
node_js:
  - lts/*
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: NFy66cl7g9HFLyqECsRWj4IaJFjAZjxM82sD/o5+LTwRxFeWpzpNtOBQdn+H9Bkw/UpoxEZ4B/Bpq8xB1NDZWs+TjpaU4SrHf89T/fEk214SwEPUjoLH7Bup7we6f5vo4uBFNTjuap5R+s/PwXopuTQqVFN0qETyEkS1tHyEanBePX57s4KQm7pCKQpXSJbEwPKLL567uETFVq0ZD3Ej9IS/IJGhE31JnNu2wDWWazmJyadA2L6FF5NeK9P32eNOoueGsIhEyhaiC3NINdFpeN2pBrgDI8IZoTYwu07g0XAQ21xSZXIB6TAuxQUcgIqh3cKIB36a25MmgpGvWjLJENTet34UI9sny/Jeib9AVIJ0Y8dLrlaofLV7ngB5HLHn8OxCxhKvaZ32XLsOa5CnBKgzpVr5OxvG4r9Us/pEe2gofpsoIjD1DoDXETyUZu4ZETEeMRRFL9Yc3+anAOSaGx99d1Y/VzeVezovzfuq8c7g0GKyxXK68eZ0ubeFiqJTVpy39YT8HWcdfefZ35sFR4gy8JDfu4CpW6u+jQ7XEH0nJLXnUaareiwBDdiEKQn12k4aLdMwquO3ZwLNCSrs6o5eW3UHHXYAjvY/dMM82jBjpYPWBwbhJ1V2Wv1BLdOoJZmXJMjkssv4VVRQzYM4qImsQhPciEibX7L9Zqe/QCA=
  app:
    master: taverna-backend-dev
