type Member {
  member: User!,
  roles: [Role]
}

type Group {
  _id: ID!
  name: String!
  image: String
  owner: User!
  roles: [Role]
  members: [Member]
}

input NewGroupInput {
  name: String!,
  image: String
}

input UpdateGroupInput {
  groupId: ID!
  name: String,
  image: String
}

extend type Query {
  getGroup(groupId: ID!): Group! @isAuth
  getMyGroups: [Group] @isAuth
}

extend type Mutation {
  createGroup(input: NewGroupInput!): Group! @isAuth
  updateGroup(input: UpdateGroupInput!): Group! @hasRoleInGroup(roles: ["isAdmin", "canManageServer"])
  deleteGroup(groupId: ID!): Group!
}
