type Role {
  _id: ID!
  isAdmin: Boolean
  canManageServer: Boolean
  canManegeRoles: Boolean
  canManageChannels: Boolean
  canKickMember: Boolean
  canBanMembers: Boolean
  canChangeNickname: Boolean
  canReadTextChannels: Boolean
  canSendMessages: Boolean
  canManageMessages: Boolean
}